import { readFileSync } from 'node:fs';

import { defineConfig, type DefaultTheme } from 'vitepress';

/**
 * The generated API sidebar, read rather than imported.
 *
 * `import … from './x.json'` needs a `with { type: 'json' }` attribute under
 * `module: nodenext`, and that attribute then has to survive whatever bundles
 * this config. Reading the file is the spelling that is true in both places,
 * and this runs in Node either way.
 */
const typedocSidebar = JSON.parse(
  readFileSync(new URL('../api/typedoc-sidebar.json', import.meta.url), 'utf8'),
) as DefaultTheme.SidebarItem[];

/**
 * VitePress, because the docs are markdown first and the site is a consequence
 * of them rather than the other way round: the same files read correctly in a
 * pull request, in an editor, and on the published page, and the build is one
 * static output with one workflow behind it.
 *
 * `base` is the root: the site is served from ngtrue.khegay.dev, not from a project page.
 */
export default defineConfig({
  title: 'ngtrue',
  description: 'Checks that keep an Angular library true.',
  base: '/',
  lastUpdated: false,
  cleanUrls: true,
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/' },
      { text: 'API', link: '/api/' },
    ],
    sidebar: [
      {
        text: 'Start here',
        items: [
          { text: 'What ngtrue is', link: '/' },
          { text: 'The three entry points', link: '/entry-points' },
          { text: 'Deprecation policy', link: '/deprecation-policy' },
        ],
      },
      {
        text: 'Exports',
        items: [
          { text: 'assertSignalFormsControl', link: '/guide/assert-signal-forms-control' },
          { text: 'unresolvedExports', link: '/guide/unresolved-exports' },
          { text: 'unresolvableTypes', link: '/guide/unresolvable-types' },
          { text: 'peerDependencyMismatches', link: '/guide/peer-dependency-mismatches' },
        ],
      },
      // Generated by `npm run docs:api`, so a new export appears here without
      // anyone editing this file.
      { text: 'API reference', items: typedocSidebar },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/thekhegay/ngtrue' }],
    footer: { message: 'MIT licensed', copyright: 'Copyright © Roman Khegay' },
  },
});
